# Generated by Django 5.2 on 2025-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival Specific'), ('fast_food', 'Fast Food'), ('main_course', 'Main Course'), ('sweets', 'Sweets'), ('drinks', 'Drinks')], default='main_course', max_length=50),
        ),
    ]
